spring.application.name=arvand-back
server.port=8091
server.address=0.0.0.0
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=arvand

spring.data.redis.lettuce.pool.max-active=20
spring.data.redis.lettuce.pool.max-idle=10
spring.data.redis.lettuce.pool.min-idle=2
spring.data.redis.lettuce.pool.max-wait=2000ms

#spring.datasource.hikari.connection-init-sql=SELECT set_limit(0.1);

redis.key.product=product:%s
redis.key.category=product:category:%s
redis.key.tag=product:tag:%s
redis.key.audience=product:audience:%s
redis.key.type=product:type:%s

redis.key.new-arrivals=product:new-arrivals
redis.key.hot-products=product:hot-products

spring.datasource.url=jdbc:postgresql://localhost:5433/arvanddb
spring.datasource.username=arvanduser
spring.datasource.password=arvandpassword1425369*
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.springframework.data.redis=debug

management.endpoints.web.exposure.include=health

opt.length=5
opt.expire=2
opt.type.login=6060
opt.type.sighUp=6065

app.develop=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
